# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MoshiHook < Formula
  desc "Portable daemon + CLI that bridges AI coding agents to the Moshi mobile app"
  homepage "https://getmoshi.app"
  version "0.2.61"

  on_macos do
    if Hardware::CPU.intel?
      url "https://cdn.getmoshi.app/hook/v0.2.61/moshi-hook_Darwin_x86_64.tar.gz"
      sha256 "8582469ad741008879ee86ffbf077d71bb456139f0442ee120ab6c082b3b40b6"

      define_method(:install) do
        bin.install "moshi-hook"
        bin.install_symlink "moshi-hook" => "moshi"
      end
    end
    if Hardware::CPU.arm?
      url "https://cdn.getmoshi.app/hook/v0.2.61/moshi-hook_Darwin_arm64.tar.gz"
      sha256 "388767dfcf4d500a218e19041070e9c39153cb8a881bb64eeb3e54909039b43c"

      define_method(:install) do
        bin.install "moshi-hook"
        bin.install_symlink "moshi-hook" => "moshi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://cdn.getmoshi.app/hook/v0.2.61/moshi-hook_Linux_x86_64.tar.gz"
      sha256 "be20d37a0b82c93ea026bd669d30a84e4820e3988121681a96c3b143e7ddfffa"
      define_method(:install) do
        bin.install "moshi-hook"
        bin.install_symlink "moshi-hook" => "moshi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://cdn.getmoshi.app/hook/v0.2.61/moshi-hook_Linux_arm64.tar.gz"
      sha256 "41398294a2ab8fbad79053208de873d3c8e03abade0b34e9a3e03a9bb8214daa"
      define_method(:install) do
        bin.install "moshi-hook"
        bin.install_symlink "moshi-hook" => "moshi"
      end
    end
  end

  def caveats
    <<~EOS
      moshi-hook is a daemon. Start it with:
        moshi-hook pair --token $MOSHI_PAIRING_TOKEN
        moshi-hook install
        brew services start moshi-hook
    EOS
  end

  service do
    run [opt_bin/"moshi-hook", "serve"]
    keep_alive true
    log_path var/"log/moshi-hook.log"
    error_log_path var/"log/moshi-hook.log"
    working_dir var
  end

  test do
    assert_match "moshi-hook", shell_output("#{bin}/moshi-hook version")
    assert_match "moshi-hook", shell_output("#{bin}/moshi version")
  end
end
