# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MoshiHook < Formula
  desc "Portable daemon + CLI that bridges AI coding agents to the Moshi mobile app"
  homepage "https://getmoshi.app"
  version "0.2.17"

  on_macos do
    if Hardware::CPU.intel?
      url "https://cdn.getmoshi.app/hook/v0.2.17/moshi-hook_Darwin_x86_64.tar.gz"
      sha256 "bac6e6539ce4af20f11f5cbd8574c391082045b9fd37bda375b681e6fe1e8b73"

      define_method(:install) do
        bin.install "moshi-hook"
        bin.install_symlink "moshi-hook" => "moshi"
      end
    end
    if Hardware::CPU.arm?
      url "https://cdn.getmoshi.app/hook/v0.2.17/moshi-hook_Darwin_arm64.tar.gz"
      sha256 "053feb37c8c5c4e10219b9f0e314d42e334c164c6fd04c3c06271f2cd9cdad97"

      define_method(:install) do
        bin.install "moshi-hook"
        bin.install_symlink "moshi-hook" => "moshi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://cdn.getmoshi.app/hook/v0.2.17/moshi-hook_Linux_x86_64.tar.gz"
      sha256 "3adb9e4dcc551bb92c79fbbf950e7fea9c66add6bbd63d44708b24bf479ead2e"
      define_method(:install) do
        bin.install "moshi-hook"
        bin.install_symlink "moshi-hook" => "moshi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://cdn.getmoshi.app/hook/v0.2.17/moshi-hook_Linux_arm64.tar.gz"
      sha256 "9d9735635ba1386fd7b1310cd17c46a72846051a4866b4c0bda4a9c4c5f249f6"
      define_method(:install) do
        bin.install "moshi-hook"
        bin.install_symlink "moshi-hook" => "moshi"
      end
    end
  end

  def caveats
    <<~EOS
      moshi-hook is a daemon. Start it with:
        moshi-hook pair --token $MOSHI_PAIRING_TOKEN
        moshi-hook install
        brew services start moshi-hook
    EOS
  end

  service do
    run [opt_bin/"moshi-hook", "serve"]
    keep_alive true
    log_path var/"log/moshi-hook.log"
    error_log_path var/"log/moshi-hook.log"
    working_dir var
  end

  test do
    assert_match "moshi-hook", shell_output("#{bin}/moshi-hook version")
    assert_match "moshi-hook", shell_output("#{bin}/moshi version")
  end
end
