# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MoshiHook < Formula
  desc "Portable daemon + CLI that bridges AI coding agents to the Moshi mobile app"
  homepage "https://getmoshi.app"
  version "0.1.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://cdn.getmoshi.app/hook/v0.1.9/moshi-hook_Darwin_x86_64.tar.gz"
      sha256 "039284e97eb811bc3f1405a2553ce8ca33c9d17b0747b44fb8eb7b1d803787c8"

      define_method(:install) do
        bin.install "moshi-hook"
      end
    end
    if Hardware::CPU.arm?
      url "https://cdn.getmoshi.app/hook/v0.1.9/moshi-hook_Darwin_arm64.tar.gz"
      sha256 "4cc29e02c3a5fa82ef5db4c9346d589752fb04b499906d8ff228470f05a7d0a3"

      define_method(:install) do
        bin.install "moshi-hook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://cdn.getmoshi.app/hook/v0.1.9/moshi-hook_Linux_x86_64.tar.gz"
      sha256 "5c3de2ff3b61d8c1ab42fcf4b460ec1ee03af042d7fc2fe1747c0f9250511232"
      define_method(:install) do
        bin.install "moshi-hook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://cdn.getmoshi.app/hook/v0.1.9/moshi-hook_Linux_arm64.tar.gz"
      sha256 "0a5965cab6536f7fbed839dcdd029f99735234ebb9c0b8703c8719ce83af8f6f"
      define_method(:install) do
        bin.install "moshi-hook"
      end
    end
  end

  def caveats
    <<~EOS
      moshi-hook is a daemon. Start it with:
        moshi-hook pair --token $MOSHI_PAIRING_TOKEN
        moshi-hook install
        brew services start moshi-hook
    EOS
  end

  service do
    run [opt_bin/"moshi-hook", "serve"]
    keep_alive true
    log_path var/"log/moshi-hook.log"
    error_log_path var/"log/moshi-hook.log"
    working_dir var
  end

  test do
    assert_match "moshi-hook", shell_output("#{bin}/moshi-hook version")
  end
end
